import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { BLOG_POSTS } from "@/data/config";
export function generateStaticParams() { return BLOG_POSTS.map((post) => ({ slug: post.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const post = BLOG_POSTS.find((item) => item.slug === slug); return post ? { title: post.title, description: post.excerpt } : {}; }
function formatDate(iso: string) { return new Date(iso).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }); }
function inlineMarkdown(text: string) { return text.replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>").replace(/`([^`]+)`/g, '<code class="rounded bg-slate-100 px-1 py-0.5 font-mono text-sm">$1</code>'); }
function renderContent(raw: string) { const lines = raw.split("\n"); const output: React.ReactNode[] = []; let i = 0; let key = 0; while (i < lines.length) { const line = lines[i]; if (line.startsWith("```")) { const code: string[] = []; i++; while (i < lines.length && !lines[i].startsWith("```")) { code.push(lines[i]); i++; } output.push(<pre key={key++} className="my-6 overflow-x-auto rounded-xl border border-slate-200 bg-slate-50 p-5 text-sm"><code>{code.join("\n")}</code></pre>); i++; continue; } if (line.startsWith("## ")) { output.push(<h2 key={key++} className="mb-3 mt-10 text-xl font-bold tracking-tight text-[#0F172A]">{line.slice(3)}</h2>); i++; continue; } if (line.startsWith("### ")) { output.push(<h3 key={key++} className="mb-2 mt-8 text-lg font-semibold text-[#0F172A]">{line.slice(4)}</h3>); i++; continue; } if (/^\d+\.\s/.test(line)) { const items: string[] = []; while (i < lines.length && /^\d+\.\s/.test(lines[i])) { items.push(lines[i].replace(/^\d+\.\s/, "")); i++; } output.push(<ol key={key++} className="my-4 list-decimal space-y-1 pl-6 text-slate-700">{items.map((item, index) => <li key={index} dangerouslySetInnerHTML={{ __html: inlineMarkdown(item) }} />)}</ol>); continue; } if (line.startsWith("- ") || line.startsWith("* ")) { const items: string[] = []; while (i < lines.length && (lines[i].startsWith("- ") || lines[i].startsWith("* "))) { items.push(lines[i].slice(2)); i++; } output.push(<ul key={key++} className="my-4 list-disc space-y-1 pl-6 text-slate-700">{items.map((item, index) => <li key={index} dangerouslySetInnerHTML={{ __html: inlineMarkdown(item) }} />)}</ul>); continue; } if (line.trim() === "") { i++; continue; } output.push(<p key={key++} className="mb-4 leading-relaxed text-slate-700" dangerouslySetInnerHTML={{ __html: inlineMarkdown(line) }} />); i++; } return output; }
export default async function BlogPostPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const post = BLOG_POSTS.find((item) => item.slug === slug); if (!post) notFound(); return <article className="mx-auto max-w-3xl px-6 py-16"><nav className="mb-8 text-sm text-slate-400" aria-label="Breadcrumb"><Link href="/blog" className="transition hover:text-slate-700">Blog</Link> <span aria-hidden="true">›</span> <span className="text-slate-700">{post.title}</span></nav><header className="mb-10"><div className="mb-4 flex flex-wrap gap-3 text-xs text-slate-400"><time dateTime={post.date}>{formatDate(post.date)}</time><span>·</span><span>{post.readingTime}</span>{post.tags.map((tag) => <span key={tag} className="rounded-full bg-slate-100 px-2.5 py-0.5">{tag}</span>)}</div><h1 className="mb-4 text-3xl font-bold tracking-tight text-[#0F172A] md:text-4xl">{post.title}</h1><p className="text-lg leading-relaxed text-slate-600">{post.excerpt}</p></header><hr className="mb-10 border-slate-100" /><div>{renderContent(post.content)}</div><hr className="mb-10 mt-14 border-slate-100" /><Link href="/blog" className="accent-text text-sm font-semibold hover:underline">← Back to Blog</Link></article>; }
